- name: Update hd-image.bash
  import_tasks: util/update_hd-image.yaml


- name: Add csip-head-node.bash
  become: yes
  copy:
    src: files/cluster/csip-head-node.bash
    dest: /usr/HD/csip-head-node.bash
    owner: root
    group: root
    mode: '0755'

- name: Install csip-head-node.bash
  become: yes
  file:
    src: /usr/HD/csip-head-node.bash
    path: /usr/local/bin/csip-head-node
    state: link


# add csip-head-node

- name: Add csip-worker-node.bash
  become: yes
  copy:
    src: files/cluster/csip-worker-node.bash
    dest: /usr/HD/csip-worker-node.bash
    owner: root
    group: root
    mode: '0755'

- name: Install csip-worker-node.bash
  become: yes
  file:
    src: /usr/HD/csip-worker-node.bash
    path: /usr/local/bin/csip-worker-node
    state: link


# Update version

- name: Update version
  import_tasks: util/update_version.yaml
  vars:
    version: '3.2.1'
